[package]
name = "interpreter"
version = "0.1.0"
authors = ["Karsten Jeschkies <k@jeschkies.xyz>"]
edition = "2018"
build = "build.rs"

[dependencies]
phf = "0.7.24"

[build-dependencies]
phf_codegen = "0.7.24"